# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
# plugins: [jekyll-paginate]
#port: 3000
safe: true
gems: 
  - jekyll-paginate
  - jekyll-redirect-from

# edit here to achieve your personal greatness
url: http://namanjain8.github.io/
title: Naman Jain
author: Naman Jain
description: Personal blog and resume
avatar: profile.jpg
resume: resume.pdf
email: jnaman806@gmail.com
github:  NamanJain8 # username
twitter: JainNaman18
linkedin: naman1811
stackoverflow: users/9471721/naman-jain   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1

# needed for travis-ci build
exclude: [vendor]

# Google Analytics
google_analytics: G-PNG8FL2V15

